version: "3.9"
services:
  database:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: "dash_driver"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    container_name: dash_driver
  database_test:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: "dash_driver_test"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3307:3306"
    container_name: "dash_driver_test"

volumes:
  pgdata:
    driver: local
